### ISSUE TITLE
Detecting the current song playing in the Spotify app?

### ISSUE THREAD

**Issue by gesabo** [Sethmr/SpotifyInSwift#2]
Thanks for posting this @Sethmr ! I was struggling with a Swift implementation and this code really helps, however I am trying to to detect the current song playing from the Spotify App itself, do you know if this is possible in the current version of the SDK?  Thanks again!

**Comment by Sethmr** [comment]
I am sorry for the delayed response. To be honest with you, I don't use Spotify. I don't know ObjC very well. I don't use Spotify in any of my Apps. My friends needed help getting it to work in his App, so I decided to replicate the App in Swift. It was far harder than I expected, so I decided to put it on Github and help out the community. I would recommend looking at how to do that in ObjC and comparing with the same spot in the Swift code.

**Comment by gesabo** [comment]
@Sethmr thanks so much, will do!
